// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: byaZbU2JReSS2QVAT9Mefp
// Component: qnoUk2omqKMZXv
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: Fd6TvYNa3aEZKP/component
import Button from "../../Button"; // plasmic-import: OFPu9JjiDm3ddD/component
import Section from "../../Section"; // plasmic-import: VIk4-pj4dsR5Y4/component
import Button2 from "../../Button2"; // plasmic-import: ICiiTTdIkpP/component

import { useScreenVariants as useScreenVariants_4R8Ap7Seox4Sus } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 4r8Ap7SEOX4SUS/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_light_saa_s_landing_page.module.css"; // plasmic-import: byaZbU2JReSS2QVAT9Mefp/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: qnoUk2omqKMZXv/css

import ChevronRightIcon from "./icons/PlasmicIcon__ChevronRight"; // plasmic-import: QjaK5yT7DZs34T/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: F6vcuMCwNPa/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: d0IP14gmaqf2s1/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: d_ZlXXRwbCR/icon

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  headerHeroSection?: p.Flex<"div">;
  classitNav?: p.Flex<typeof Navbar>;
  welcomeHeader?: p.Flex<"h1">;
  computerDashboardImage?: p.Flex<typeof p.PlasmicImg>;
  builtFor?: p.Flex<typeof Section>;
  builtForSection?: p.Flex<"div">;
  shortMessage?: p.Flex<typeof Section>;
  whatMakesUsDifferent?: p.Flex<typeof Section>;
  features?: p.Flex<typeof Section>;
  allClassitFeatures?: p.Flex<typeof Section>;
  moreToCome?: p.Flex<typeof Section>;
  pricingPlans?: p.Flex<typeof Section>;
  accessiblePlans?: p.Flex<"h2">;
  independentStudentsPricing?: p.Flex<"h4">;
  ourMission?: p.Flex<typeof Section>;
  signUpForUpdates?: p.Flex<typeof Section>;
  about?: p.Flex<typeof Button2>;
  link?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultHomepageProps {}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_4R8Ap7Seox4Sus()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />

        <title key="title">{"Home"}</title>

        <meta key="og:title" property="og:title" content={"Home"} />

        <meta key="twitter:title" name="twitter:title" content={"Home"} />

        <meta
          key="description"
          name="description"
          content={"Learning management system for the future generation. "}
        />

        <meta
          key="og:description"
          property="og:description"
          content={"Learning management system for the future generation. "}
        />

        <meta
          key="twitter:description"
          name="twitter:description"
          content={"Learning management system for the future generation. "}
        />

        <meta
          key="og:image"
          property="og:image"
          content={
            "https://site-assets.plasmic.app/c5970f28c8d9aeaeb2d4ca5eb415a127.jpg"
          }
        />

        <meta
          key="twitter:image"
          name="twitter:image"
          content={
            "https://site-assets.plasmic.app/c5970f28c8d9aeaeb2d4ca5eb415a127.jpg"
          }
        />

        <link ref="canonical" href={"classit.me"} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"headerHeroSection"}
              data-plasmic-override={overrides.headerHeroSection}
              hasGap={true}
              className={classNames(projectcss.all, sty.headerHeroSection)}
            >
              {true ? (
                <Navbar
                  data-plasmic-name={"classitNav"}
                  data-plasmic-override={overrides.classitNav}
                  className={classNames("__wab_instance", sty.classitNav)}
                />
              ) : null}

              <div className={classNames(projectcss.all, sty.freeBox__ouu7A)}>
                <div className={classNames(projectcss.all, sty.freeBox__oz6Pe)}>
                  <h1
                    data-plasmic-name={"welcomeHeader"}
                    data-plasmic-override={overrides.welcomeHeader}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.welcomeHeader
                    )}
                  >
                    {"Welcome to the LMS of the future."}
                  </h1>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2LhNt
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#000000", fontWeight: 700 }}
                      >
                        {"Learning management system"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#000000", fontWeight: 700 }}
                      >
                        {"for the future generation"}
                      </span>
                    </React.Fragment>
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__uzGcR)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__m3SXc
                      )}
                      color={"clear" as const}
                      link={"#" as const}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xtozk
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobile") ? (
                          "Learn More"
                        ) : (
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#FFC900" }}
                            >
                              {"Learn More"}
                            </span>
                          </React.Fragment>
                        )}
                      </div>
                    </Button>
                  </p.Stack>
                </div>

                <p.PlasmicImg
                  data-plasmic-name={"computerDashboardImage"}
                  data-plasmic-override={overrides.computerDashboardImage}
                  alt={""}
                  className={classNames(sty.computerDashboardImage)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"1140px" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/light_saa_s_landing_page/images/screenshot7Png.png",
                    fullWidth: 1083,
                    fullHeight: 702,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>
          ) : null}

          <Section
            data-plasmic-name={"builtFor"}
            data-plasmic-override={overrides.builtFor}
            className={classNames("__wab_instance", sty.builtFor)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? ("fullContentWidth" as const)
                : ("fullContentWidth" as const)
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__m7TWy)}>
              <div className={classNames(projectcss.all, sty.freeBox__oznOq)}>
                <div
                  data-plasmic-name={"builtForSection"}
                  data-plasmic-override={overrides.builtForSection}
                  className={classNames(projectcss.all, sty.builtForSection)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__yCfsp)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__iJ1Gv
                      )}
                    >
                      {"Educators"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dmM7J
                      )}
                    >
                      {
                        "Clean layout to simplify the way you plan and grade lessons. CLASSIT is built to help keep your students engaged, while making it easier to stay connected with parents. "
                      }
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__zw3Vg)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___3CJyq
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobile")
                        ? "Students"
                        : "Students"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kPLv7
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobile")
                        ? "Personalize the way you learn with CLASSIT. Boost your productivity while staying connected to your friends and teachers with CLASSIT. "
                        : "Personalize the way you learn with CLASSIT. Boost your productivity while staying connected to your friends and teachers with CLASSIT. "}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__wiwok)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___16ID
                      )}
                    >
                      {"Parents"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wcJdm
                      )}
                    >
                      {
                        "Stay connected with your student(s) and their teachers throughout the day with CLASSIT. No hassle messaging and grade checking. "
                      }
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Section>

          <Section
            data-plasmic-name={"shortMessage"}
            data-plasmic-override={overrides.shortMessage}
            className={classNames("__wab_instance", sty.shortMessage)}
          >
            <div className={classNames(projectcss.all, sty.columns___2Kj6)}>
              <div className={classNames(projectcss.all, sty.column__thU8G)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cCpkj
                  )}
                >
                  {"Built to empower \nand connect!"}
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__nfyIe)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fJxa4
                  )}
                >
                  {
                    "Keeping learning personal, while helping to build connections between students, teachers, and parents. "
                  }
                </div>
              </div>
            </div>
          </Section>

          <Section
            data-plasmic-name={"whatMakesUsDifferent"}
            data-plasmic-override={overrides.whatMakesUsDifferent}
            className={classNames("__wab_instance", sty.whatMakesUsDifferent)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? ("fullContentWidth" as const)
                : undefined
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__dtZyT)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__uh3EP
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "Lorem Ipsum"
                  : "What makes us different?"}
              </h2>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__t7MoF
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#000000" }}
                  >
                    {
                      "CLASSIT is student focused. This means that the platform is built to cater to the needs of K-12 students. Our platform allows students to customize the interface to fit their productivity needs. "
                    }
                  </span>
                </React.Fragment>
              </div>
            </div>
          </Section>

          <Section
            data-plasmic-name={"features"}
            data-plasmic-override={overrides.features}
            className={classNames("__wab_instance", sty.features)}
          >
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1__yQsRu
              )}
            >
              {"Features"}
            </h1>
          </Section>

          <Section
            data-plasmic-name={"allClassitFeatures"}
            data-plasmic-override={overrides.allClassitFeatures}
            className={classNames("__wab_instance", sty.allClassitFeatures)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? ("fullContentWidth" as const)
                : ("fullContentWidth" as const)
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__bVikn)}>
              <div className={classNames(projectcss.all, sty.columns__siMV)}>
                <div className={classNames(projectcss.all, sty.column__xDqee)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__slO6K)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"500px" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? ("284px" as const)
                        : ("auto" as const)
                    }
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/messyDoodlepng.png",
                      fullWidth: 1024,
                      fullHeight: 768,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__ezgha)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ou4JJ)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__lPw4U)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___0Ehek)}
                        displayHeight={"2px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"26px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/light_saa_s_landing_page/images/lineBluesvg.svg",
                          fullWidth: 300,
                          fullHeight: 23,
                          aspectRatio: 13
                        }}
                      />
                    </div>

                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__e0TdT
                      )}
                    >
                      {"Curriculum and Course Management"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__k05Ur
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__ksu1O
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__twbEe
                              )}
                            >
                              {"Curriculum and Course Management"}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__uV1
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__dewAf
                              )}
                            >
                              {"Integrated Assessment Experience"}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__yy60D
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__gc7Tx
                              )}
                            >
                              {"Grades and GPA Calculation"}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__hNy2
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__oJhUb
                              )}
                            >
                              {"Assignment Management"}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul___1JvM7
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__qo3Ux
                              )}
                            >
                              {"Attendance tracker"}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__unkj7)}>
              <div className={classNames(projectcss.all, sty.columns__j4Niq)}>
                <div className={classNames(projectcss.all, sty.column__lq0Sa)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vrQtb)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__farCf)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__iy9Dk)}
                        displayHeight={"2px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"26px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/light_saa_s_landing_page/images/lineBluesvg.svg",
                          fullWidth: 300,
                          fullHeight: 23,
                          aspectRatio: 13
                        }}
                      />
                    </div>

                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___3Nj9Y
                      )}
                    >
                      {"Collaborative Workspaces for students and teachers"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__g9M0
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__ek8Nr
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__zMaq
                              )}
                            >
                              {"Group forums "}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__vdMbr
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__mYdDc
                              )}
                            >
                              {"Private message"}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__pzzNu
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li___0QoNk
                              )}
                            >
                              {"Dual Accounts: Personal & School"}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul___5Dn7
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li___7RC1B
                              )}
                            >
                              {"Live Status"}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__trCUb
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__s3S7H
                              )}
                            >
                              {"Announcements"}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__dkosq)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__qg5Zt)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? ("284px" as const)
                        : ("500px" as const)
                    }
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? ("284px" as const)
                        : ("auto" as const)
                    }
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/readingSideDoodlepng.png",
                      fullWidth: 1024,
                      fullHeight: 768,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__lwvPh)}>
              <div className={classNames(projectcss.all, sty.columns__jPXr)}>
                <div className={classNames(projectcss.all, sty.column__g9Wjs)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__sxJD)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? ("284px" as const)
                        : ("500px" as const)
                    }
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/floatDoodlepng.png",
                      fullWidth: 1024,
                      fullHeight: 768,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__dvkxX)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__rqb8Z)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ehmkd)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__xamHj)}
                        displayHeight={"2px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"26px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/light_saa_s_landing_page/images/lineBluesvg.svg",
                          fullWidth: 300,
                          fullHeight: 23,
                          aspectRatio: 13
                        }}
                      />
                    </div>

                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___6RAr5
                      )}
                    >
                      {"Personalized learning interface"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zkp0B
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__rAyNx
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__qLxcq
                              )}
                            >
                              {"Schedule Management"}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__liCpl
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__mwVcm
                              )}
                            >
                              {"User interface customization"}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__yK3H2
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__tHSdr
                              )}
                            >
                              {"Personalized focus timer"}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__jDoBt
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__qJdP2
                              )}
                            >
                              {"Customizable task list "}
                            </li>
                          </ul>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Section>

          <Section
            data-plasmic-name={"moreToCome"}
            data-plasmic-override={overrides.moreToCome}
            className={classNames("__wab_instance", sty.moreToCome)}
            size={"fullContentWidth" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vo2Dc
              )}
            >
              {"More features to come"}
            </div>
          </Section>

          <Section
            data-plasmic-name={"pricingPlans"}
            data-plasmic-override={overrides.pricingPlans}
            background={"blue" as const}
            className={classNames("__wab_instance", sty.pricingPlans)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? ("fullContentWidth" as const)
                : ("fullContentWidth" as const)
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__tn5Dv)}>
              <h2
                data-plasmic-name={"accessiblePlans"}
                data-plasmic-override={overrides.accessiblePlans}
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.accessiblePlans
                )}
              >
                {"Keeping CLASSIT accessible"}
              </h2>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___81Uch
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                  : "We aim to keep CLASSIT free for all learners. We do charge a small fee for teachers and custom pricing for schools. "}
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__o4Si)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__ji42)}>
                  <h4
                    data-plasmic-name={"independentStudentsPricing"}
                    data-plasmic-override={overrides.independentStudentsPricing}
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.independentStudentsPricing
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Starter"
                      : "Independent Students"}
                  </h4>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__y5Vak
                    )}
                  >
                    {"All verified students get full access  "}
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__p0Uew)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"238px" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/linesvg.svg",
                      fullWidth: 300,
                      fullHeight: 3,
                      aspectRatio: 119
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__xklm8)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__m0Auo
                      )}
                    >
                      {"$0"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7YaVl
                      )}
                    >
                      {"/ Month"}
                    </div>
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__sPgXg)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"238px" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/linesvg.svg",
                      fullWidth: 300,
                      fullHeight: 3,
                      aspectRatio: 119
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jm4Fw
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Feature"
                      : "Feature"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__rjzpa)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__r98Lb)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__sk2Uw
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__uw1Tq)}
                          displayHeight={"20px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"20px" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/light_saa_s_landing_page/images/tickCircleBluesvg.svg",
                            fullWidth: 150,
                            fullHeight: 150,
                            aspectRatio: 1
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__k2R3Z
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ubGn
                          )}
                        >
                          {"Unlimited issue"}
                        </div>
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___2Kx23
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yVrIw
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__eo0Z)}
                          displayHeight={"20px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"20px" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/light_saa_s_landing_page/images/tickCircleBluesvg.svg",
                            fullWidth: 150,
                            fullHeight: 150,
                            aspectRatio: 1
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__aoBaz
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jamnX
                          )}
                        >
                          {"Free domain"}
                        </div>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__dD6Da)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vClx5
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__nsDB)}
                          displayHeight={"20px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"20px" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/light_saa_s_landing_page/images/tickCircleBluesvg.svg",
                            fullWidth: 150,
                            fullHeight: 150,
                            aspectRatio: 1
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kyJ5
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__o72Hc
                          )}
                        >
                          {"3 team accounts"}
                        </div>
                      </div>
                    </div>
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__hipnN)}
                    color={"blue" as const}
                    link={"#" as const}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3LwwZ
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobile")
                        ? "Get Started"
                        : "Coming soon"}
                    </div>
                  </Button>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__wrtCz)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ieC
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Our Recommendation"
                      : "Our Recommendation"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__xGOeq)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__yu0V9
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobile")
                        ? "Pro"
                        : "Independent Educators "}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kMfQw
                      )}
                    >
                      {
                        "Get CLASSIT features even if your school isn't registered. "
                      }
                    </div>

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__sNqm)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"238px" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/linesvg.svg",
                        fullWidth: 300,
                        fullHeight: 3,
                        aspectRatio: 119
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__fxfZz)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__iT1M3
                        )}
                      >
                        {"$3"}
                      </h3>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hkQBp
                        )}
                      >
                        {"/ Month"}
                      </div>
                    </div>

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__j5FO)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"238px" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/linesvg.svg",
                        fullWidth: 300,
                        fullHeight: 3,
                        aspectRatio: 119
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rz5Ql
                      )}
                    >
                      {"Feature"}
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__w5Ku8)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__wKoCf
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__iEjbQ
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__qiOej)}
                            displayHeight={"20px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"20px" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/light_saa_s_landing_page/images/tickCircleBluesvg.svg",
                              fullWidth: 150,
                              fullHeight: 150,
                              aspectRatio: 1
                            }}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__urM5A
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rbh2P
                            )}
                          >
                            {"7 Classrooms"}
                          </div>
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xhRqc
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__jQnCu
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__xy13S)}
                            displayHeight={"20px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"20px" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/light_saa_s_landing_page/images/tickCircleBluesvg.svg",
                              fullWidth: 150,
                              fullHeight: 150,
                              aspectRatio: 1
                            }}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lQe7G
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jKqab
                            )}
                          >
                            {"Up to 30 students per class"}
                          </div>
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ttUej
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__a8NGx
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__sxvGa)}
                            displayHeight={"20px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"20px" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/light_saa_s_landing_page/images/tickCircleBluesvg.svg",
                              fullWidth: 150,
                              fullHeight: 150,
                              aspectRatio: 1
                            }}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__aB2Re
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__w4ADr
                            )}
                          >
                            {"Limited school features"}
                          </div>
                        </div>
                      </div>
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__p3KVx
                      )}
                      color={"blue" as const}
                      link={"#" as const}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__exf3
                        )}
                      >
                        {"Coming soon"}
                      </div>
                    </Button>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__iQLgx)}>
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__ljsDv
                    )}
                  >
                    {"Schools"}
                  </h4>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9Iw4
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
                      : "Connect all students, Educators, parents, and admin on one platform. "}
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__hhhtm)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"238px" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/linesvg.svg",
                      fullWidth: 300,
                      fullHeight: 3,
                      aspectRatio: 119
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__lOsaE)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__zu08
                      )}
                    >
                      {"$$$"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9KdVp
                      )}
                    >
                      {"/ Month"}
                    </div>
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__gtjqd)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"238px" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/linesvg.svg",
                      fullWidth: 300,
                      fullHeight: 3,
                      aspectRatio: 119
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__adAsh
                    )}
                  >
                    {"Feature"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__mpT3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wID)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bj47H
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__dDsV6)}
                          displayHeight={"20px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"20px" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/light_saa_s_landing_page/images/tickCircleBluesvg.svg",
                            fullWidth: 150,
                            fullHeight: 150,
                            aspectRatio: 1
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__m6OQp
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__w99GK
                          )}
                        >
                          {"Unlimited issue"}
                        </div>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__zytr8)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bYe2A
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__sbxzJ)}
                          displayHeight={"20px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"20px" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/light_saa_s_landing_page/images/tickCircleBluesvg.svg",
                            fullWidth: 150,
                            fullHeight: 150,
                            aspectRatio: 1
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__woIk
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rXaN
                          )}
                        >
                          {"Digital pass sytem"}
                        </div>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__lsOV)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___3JrB2
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__yflKd)}
                          displayHeight={"20px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"20px" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/light_saa_s_landing_page/images/tickCircleBluesvg.svg",
                            fullWidth: 150,
                            fullHeight: 150,
                            aspectRatio: 1
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mkMw
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__aitwl
                          )}
                        >
                          {"Full educators and students features"}
                        </div>
                      </div>
                    </div>
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__xelMx)}
                    color={"blue" as const}
                    link={"#" as const}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sX5Ma
                      )}
                    >
                      {"Get Started"}
                    </div>
                  </Button>
                </div>
              </p.Stack>
            </div>
          </Section>

          <Section
            data-plasmic-name={"ourMission"}
            data-plasmic-override={overrides.ourMission}
            className={classNames("__wab_instance", sty.ourMission)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? ("fullContentWidth" as const)
                : ("faq" as const)
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__cXgxj)}>
              <div className={classNames(projectcss.all, sty.freeBox___8LSZi)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__vJGzM
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "Our mission"
                    : "Our mission"}
                </h2>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox___02Ht0)}>
                <div className={classNames(projectcss.all, sty.freeBox__jw2Bt)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__at39K
                    )}
                  >
                    {
                      "CLASSIT inc is a web-based tool that allows students, teachers, and parents to network efficiently.  CLASSIT inc platform will enable teachers to easily communicate with their students and parents. Capabilities include assigning digital passes, homework, classwork, and exams. Outside of school, students will be able to use a public forum to ask others for help on assignments, set study focus timers, and manage their schedules. "
                    }
                  </div>
                </div>
              </div>
            </div>
          </Section>

          <Section
            data-plasmic-name={"signUpForUpdates"}
            data-plasmic-override={overrides.signUpForUpdates}
            className={classNames("__wab_instance", sty.signUpForUpdates)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? ("fullContentWidth" as const)
                : ("fullContentWidth" as const)
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__qLmX7)}>
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__pfXs1
                )}
              >
                {"SIGN UP FOR CLASSIT UPDATES"}
              </h1>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__krIt3
                )}
              >
                {
                  "CLASSIT is under construction as of right now. Come back soon and sign up to be one of the first users of our platform! "
                }
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__umtJv)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns___5X9NA)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__hSmYv)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__pJy)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__hoPpA)}
                        displayHeight={"40px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"40px" as const}
                        src={{
                          src: "/plasmic/light_saa_s_landing_page/images/img0773Jpeg.jpeg",
                          fullWidth: 1276,
                          fullHeight: 1178,
                          aspectRatio: undefined
                        }}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yn4L0
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__feR52
                          )}
                        >
                          {"Connect with us"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lcaD
                          )}
                        >
                          <Icon28Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__yhRpa
                            )}
                            role={"img"}
                          />
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__qec09)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__cWpB)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fo9M4
                        )}
                      >
                        {"Product"}
                      </div>

                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__moq8Q
                        )}
                        color={"clear" as const}
                        endIcon={
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__egz6Q
                            )}
                            role={"img"}
                          />
                        }
                        size={"minimal" as const}
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__hvHlT
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lKsJa
                          )}
                        >
                          {"Pricing"}
                        </div>
                      </Button2>

                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__i55Ou
                        )}
                        color={"clear" as const}
                        endIcon={
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__i7ArG
                            )}
                            role={"img"}
                          />
                        }
                        size={"minimal" as const}
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___8XuMn
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tv6Dj
                          )}
                        >
                          {"Sign up"}
                        </div>
                      </Button2>
                    </p.Stack>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___44SiT)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__et1Ru)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__h0KeB
                        )}
                      >
                        {"Support"}
                      </div>

                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2___9SRnp
                        )}
                        color={"clear" as const}
                        endIcon={
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__pZ5Hq
                            )}
                            role={"img"}
                          />
                        }
                        size={"minimal" as const}
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__bkRqB
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pbuLz
                          )}
                        >
                          {"FAQs"}
                        </div>
                      </Button2>

                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__np2H2
                        )}
                        color={"clear" as const}
                        endIcon={
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__jXjpV
                            )}
                            role={"img"}
                          />
                        }
                        size={"minimal" as const}
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ccbJz
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zhyN0
                          )}
                        >
                          {"Status"}
                        </div>
                      </Button2>
                    </p.Stack>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__lL2Zd)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__rdYbX)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tE3S
                        )}
                      >
                        {"Company"}
                      </div>

                      <Button2
                        data-plasmic-name={"about"}
                        data-plasmic-override={overrides.about}
                        className={classNames("__wab_instance", sty.about)}
                        color={"clear" as const}
                        endIcon={
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__qc1P4
                            )}
                            role={"img"}
                          />
                        }
                        link={undefined}
                        size={"minimal" as const}
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__lYHs
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <p.PlasmicLink
                          data-plasmic-name={"link"}
                          data-plasmic-override={overrides.link}
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link
                          )}
                          component={Link}
                          platform={"nextjs"}
                        >
                          {"About"}
                        </p.PlasmicLink>
                      </Button2>

                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__lWZt7
                        )}
                        color={"clear" as const}
                        endIcon={
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xDjw1
                            )}
                            role={"img"}
                          />
                        }
                        size={"minimal" as const}
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xT8C3
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__aRzUw
                          )}
                        >
                          {"Contact us"}
                        </div>
                      </Button2>
                    </p.Stack>
                  </div>
                </p.Stack>
              </div>
            </div>
          </Section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerHeroSection",
    "classitNav",
    "welcomeHeader",
    "computerDashboardImage",
    "builtFor",
    "builtForSection",
    "shortMessage",
    "whatMakesUsDifferent",
    "features",
    "allClassitFeatures",
    "moreToCome",
    "pricingPlans",
    "accessiblePlans",
    "independentStudentsPricing",
    "ourMission",
    "signUpForUpdates",
    "about",
    "link"
  ],
  headerHeroSection: [
    "headerHeroSection",
    "classitNav",
    "welcomeHeader",
    "computerDashboardImage"
  ],
  classitNav: ["classitNav"],
  welcomeHeader: ["welcomeHeader"],
  computerDashboardImage: ["computerDashboardImage"],
  builtFor: ["builtFor", "builtForSection"],
  builtForSection: ["builtForSection"],
  shortMessage: ["shortMessage"],
  whatMakesUsDifferent: ["whatMakesUsDifferent"],
  features: ["features"],
  allClassitFeatures: ["allClassitFeatures"],
  moreToCome: ["moreToCome"],
  pricingPlans: [
    "pricingPlans",
    "accessiblePlans",
    "independentStudentsPricing"
  ],
  accessiblePlans: ["accessiblePlans"],
  independentStudentsPricing: ["independentStudentsPricing"],
  ourMission: ["ourMission"],
  signUpForUpdates: ["signUpForUpdates", "about", "link"],
  about: ["about", "link"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerHeroSection: "div";
  classitNav: typeof Navbar;
  welcomeHeader: "h1";
  computerDashboardImage: typeof p.PlasmicImg;
  builtFor: typeof Section;
  builtForSection: "div";
  shortMessage: typeof Section;
  whatMakesUsDifferent: typeof Section;
  features: typeof Section;
  allClassitFeatures: typeof Section;
  moreToCome: typeof Section;
  pricingPlans: typeof Section;
  accessiblePlans: "h2";
  independentStudentsPricing: "h4";
  ourMission: typeof Section;
  signUpForUpdates: typeof Section;
  about: typeof Button2;
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    classitNav: makeNodeComponent("classitNav"),
    welcomeHeader: makeNodeComponent("welcomeHeader"),
    computerDashboardImage: makeNodeComponent("computerDashboardImage"),
    builtFor: makeNodeComponent("builtFor"),
    builtForSection: makeNodeComponent("builtForSection"),
    shortMessage: makeNodeComponent("shortMessage"),
    whatMakesUsDifferent: makeNodeComponent("whatMakesUsDifferent"),
    features: makeNodeComponent("features"),
    allClassitFeatures: makeNodeComponent("allClassitFeatures"),
    moreToCome: makeNodeComponent("moreToCome"),
    pricingPlans: makeNodeComponent("pricingPlans"),
    accessiblePlans: makeNodeComponent("accessiblePlans"),
    independentStudentsPricing: makeNodeComponent("independentStudentsPricing"),
    ourMission: makeNodeComponent("ourMission"),
    signUpForUpdates: makeNodeComponent("signUpForUpdates"),
    about: makeNodeComponent("about"),
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
